import { NextResponse } from "next/server";
import { z } from "zod";
import { parseTravelerRequest } from "@/lib/domain/traveler-parser";

const bodySchema = z.object({
  text: z.string().trim().min(1).max(1200),
  entryMode: z.enum(["ai-plan", "existing-plan", "near-me"]).optional(),
  startPoint: z.string().trim().max(180).optional(),
  locationConsent: z.enum(["granted", "denied", "not-requested"]).default("not-requested"),
  coordinates: z
    .object({
      latitude: z.number().min(-90).max(90),
      longitude: z.number().min(-180).max(180),
    })
    .optional(),
  locationAccuracyMeters: z.number().nonnegative().max(100000).optional(),
});

export async function POST(request: Request) {
  try {
    const body = bodySchema.parse(await request.json());
    const parsed = parseTravelerRequest(body.text, {
      entryMode: body.entryMode,
      startPoint: body.startPoint || undefined,
      locationConsent: body.locationConsent,
      coordinates: body.coordinates,
      locationAccuracyMeters: body.locationAccuracyMeters,
    });

    return NextResponse.json({
      parsed,
      meta: {
        mode: "deterministic-demo",
        factsPolicy: "No place or cafe fact is generated by the parser.",
      },
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { message: "ข้อมูลยังไม่ครบ กรุณาตรวจข้อความแล้วลองอีกครั้ง", issues: error.issues },
        { status: 400 },
      );
    }

    return NextResponse.json(
      { message: "ยังแปลคำขอนี้ไม่ได้ ข้อความของคุณยังไม่หาย กรุณาลองอีกครั้ง" },
      { status: 500 },
    );
  }
}
